language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  global:
  - PACKAGE=tree_layout
  - secure: OEKYnW2f9LQfk5QDZfy2ZRmRy9ELuyEpZ41dgYWCGDzxYw+1Lp1vCxh+xvjQ8u2+wJIcNtlFbWi0faieK2+yJgx8GRoEmbkfVoprQO5zw1Rx7RyMV34zK4DE5hD1e7C2JgYc+WJC1e+4JVVSP4Tft/fEs4jyV8e7L3SqZKqwTI/dpI7KNCGujYGj1D0j/LBQUu9t/DBqtvJX/l/iYoV8CYF3IzLZkCy75LfbbIrqt15eXlKgVmtL3P+ZCUM9GOiAZoBXZcxRkUf/HcjVXOdEQ/eJrR7BAf7riPA+7zpjabnKw40UIf10OZ78a05hLLCca+YINfQJzcWr+Tlmjv7gGcU1WWuX+NX0+b8K2kQUGhTe+oJk5wt133XPSS+2hlSaQZRUAkq0nUss0TmtSRgbYJ3FsQpJOAqYXU1+JmYIAU6YxfeoZoufJH3uXl1Y0Ax0HeQM9m+u5xU5hXpnbrvrmI3yW5sLXIO5kmhSQY6eAmjqUvZlqtc6igKamf4mgI09Aho5QWZFXkGVisT/af418aQ0BGNKR3UvPH+vwT0OsqhPIMxtDiNkpnMnZHC8V4vUajengYASstgUeVHph45BcuHdJFoJMt/CXn2lxWYGjigSdl32WwgY/MgiLjmuL4OrZbxbJOlBXvrR/ZrkyhD8TGqAjF30wGhOc4KRptiL5co=
  matrix:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07 DOC=true
