language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  global:
  - PACKAGE=tree_layout
  - secure: wge17LAsPgfP39JEA1QTiRT/t6pMiz/WeqF88VfeephDtnSj91YoABc90SIj9CeedfMC6jE0g3/rxiHley7Jb4yZULK9NCekgE4fPRLvj5FSj2+AAaoSLPL+cPK8tiWcnyTq2wvp/+G4RW8vqCShhUTc2MS16ze6jbbPXARKF9+2pGb0F6d0YbOcuCjv7oUax07mvKOVOIwi61sdbZ+nZsKPp+k47KJzyQMOaTebFnhaZm1YxXvhwO5Zw4ixQk4Wn1b/OJBN9cI4lfQCUZtp8y/Hn6tDIXV8pkAv2M+Xwi2eHV7H2jaYdEoP6bPwA6yH3mrLe+S9+Nen903Uv1bPeVyCVj8YOD9+SHODc8dwZF8xVWMTIaru0p9Hobmx+v7tL0P22jlu6ucDmE/Pl2j7BYe+EtksTwr3Iw0faqbL62Jh+bDG06PUAPBegTOa2OYmxOSVC7ol559pbDm08gTGyaI09zGtbPRGKuw/jSIlyjCygG5YIM3Qgbc3baa0Y083mueZl6904KNM08zLSolO/Xjwu+TPRyRl+Os1KxIIh4mjV8VVyCkksFECvGEtCC3Om7iDvt5ROV0LIzNSbh+X3L6z1mgoXewNOMVWSNL8UqEjX2DRVkM5b0NsqVTgFXsf9TrE8AZU6VEJvjtbp8hR//Q6XWctSKrcECfJvAo+u9U=
  matrix:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07 DOC=true
